# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:r)
variables:
  GO_VERSION: 1.12.5
  GOPATH: $(Agent.BuildDirectory)/go

jobs:
  - job: Checks
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 30
    steps:
    - template: azp-dependencies.yml
    - checkout: self
    - script: make basic-checks
      displayName: Run checks

  - job: UnitTest
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 120
    steps:
    - template: azp-dependencies.yml
    - checkout: self
    - script: |
        # TODO: remove when fabric-mod supports sampleconfig outside GOPATH
        mkdir -p ${GOPATH}/src/github.com/hyperledger/fabric
        cp -R sampleconfig ${GOPATH}/src/github.com/hyperledger/fabric
        make unit-test
      displayName: Run unit test
    - script: bash <(curl https://codecov.io/bash)
      displayName: Upload coverage to Codecov 

  - job: IntegrationTest
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 120
    steps:
    - template: azp-dependencies.yml
    - checkout: self
    - script: make integration-test
      displayName: Run integration test
